---
- name: Install common Debian/Ubuntu packages
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
      - iptables
      - iproute2
      - nfs-common
      - open-iscsi
      - jq
      - unzip
    state: present
    update_cache: true
