---
- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
  when: ansible_os_family == 'Debian'

- name: Enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: ansible_system == 'Linux'
