---
- name: Deploy urban-platform Helm release
  hosts: localhost
  gather_facts: false
  vars:
    namespace: urban-platform
  tasks:
    - name: Deploy Helm chart
      kubernetes.core.helm:
        name: urban-platform-infra
        chart_ref: helm/urban-platform-infra
        release_namespace: "{{ namespace }}"
        create_namespace: true
        values_files:
          - helm/urban-platform-infra/values.yaml
