apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: city-intersection-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.example.com/platform/city-intersection-project.git
    targetRevision: main
    path: helm/city-intersection-platform
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: city-intersection
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
