apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: urban-platform-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.example.com/platform/urban-platform-infra.git
    targetRevision: main
    path: helm/urban-platform-infra
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: urban-platform
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
