#!/usr/bin/env python3
"""Generate and execute guarded Compose-to-platform migration automation."""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import stat
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError:  # pragma: no cover - exercised by operator setup.
    yaml = None

import import_project


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VALUES = ROOT / "helm/urban-platform-infra/values.yaml"
SECRET_ENV_RE = import_project.SECRET_KEY_RE
GENERATED_HEADER = "# Generated by scripts/migrate_project.py. Keep private outputs out of Git.\n"


def require_yaml() -> None:
    if yaml is None:
        raise SystemExit("PyYAML is required. Install it with `python3 -m pip install PyYAML`.")


def k8s_name(value: str, prefix: str = "") -> str:
    safe = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    safe = re.sub(r"-+", "-", safe) or "item"
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:8]
    base = f"{prefix}-{safe}" if prefix else safe
    base = base[:52].strip("-")
    return f"{base}-{digest}"[:63].strip("-")


def relative_compose_file(project_path: Path, file_name: str) -> Path:
    return project_path / file_name


def load_context(args: argparse.Namespace) -> tuple[Path, list[Path], list[tuple[import_project.ServiceRecord, dict[str, Any]]], list[import_project.Finding], dict[str, Any]]:
    require_yaml()
    project_path = Path(args.project_path).expanduser().resolve()
    if not project_path.exists() or not project_path.is_dir():
        raise SystemExit(f"Project path does not exist or is not a directory: {project_path}")

    values_path = Path(args.values).expanduser()
    if not values_path.is_absolute():
        values_path = (ROOT / values_path).resolve()
    policy_path = Path(args.image_policy).expanduser()
    if not policy_path.is_absolute():
        policy_path = (ROOT / policy_path).resolve()

    values = import_project.load_yaml(values_path)
    approved_images = import_project.normalize_approved_images(policy_path)
    selected_ingress = args.ingress_controller or values.get("ingress", {}).get("className", "traefik")
    selected_webserver = args.webserver or values.get("webserver", {}).get("provider", "nginx")
    selected_database = args.database or values.get("databases", {}).get("provider", "cloudnative-pg")
    expected_web_image = import_project.expected_webserver_image(values, selected_webserver)

    findings: list[import_project.Finding] = []
    compose_files = import_project.find_compose_files(project_path)
    service_pairs = import_project.read_compose_services(project_path, compose_files, findings)
    for record, service in service_pairs:
        import_project.analyze_service(
            service=service,
            record=record,
            findings=findings,
            approved_images=approved_images,
            selected_ingress=str(selected_ingress),
            selected_webserver=str(selected_webserver),
            selected_database=str(selected_database),
            expected_web_image=expected_web_image,
        )
    return project_path, compose_files, service_pairs, findings, values


def secret_entries(service: dict[str, Any]) -> dict[str, str]:
    entries: dict[str, str] = {}
    for key, value in import_project.environment_entries(service.get("environment")):
        if not SECRET_ENV_RE.search(key):
            continue
        if value is None or import_project.VARIABLE_VALUE_RE.match(value):
            continue
        entries[key] = value
    return entries


def postgres_env(service: dict[str, Any]) -> dict[str, str]:
    env = {key: value for key, value in import_project.environment_entries(service.get("environment")) if value is not None}
    return {
        "user": env.get("POSTGRES_USER", "postgres"),
        "password": env.get("POSTGRES_PASSWORD", ""),
        "database": env.get("POSTGRES_DB", env.get("POSTGRES_USER", "postgres")),
    }


def published_port(record: import_project.ServiceRecord, target: str = "5432") -> str | None:
    for port in record.ports:
        if port.target == target and port.published:
            return port.published
    return None


def read_database_targets(path: str | None) -> dict[str, str]:
    if not path:
        return {}
    target_path = Path(path).expanduser()
    if not target_path.exists():
        raise SystemExit(f"Database target map does not exist: {target_path}")
    data = yaml.safe_load(target_path.read_text(encoding="utf-8")) or {}
    targets = data.get("databaseTargets", data)
    if not isinstance(targets, dict):
        raise SystemExit("Database target map must be a mapping or contain `databaseTargets`.")
    return {str(key): str(value) for key, value in targets.items()}


def run_command(command: list[str], *, env: dict[str, str] | None = None, stdin: str | None = None, cwd: Path | None = None) -> None:
    display = " ".join(command)
    print(f"+ {display}")
    subprocess.run(command, input=stdin, text=True, env=env, cwd=str(cwd) if cwd else None, check=True)


def write_file(path: Path, content: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if executable:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)


def generate_bundle(
    args: argparse.Namespace,
    project_path: Path,
    service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]],
    findings: list[import_project.Finding],
    values: dict[str, Any],
) -> None:
    output = Path(args.output).expanduser()
    output.mkdir(parents=True, exist_ok=True)
    redactor = import_project.ReportRedactor(args.redact_sensitive)
    service_records = [record for record, _service in service_pairs]
    database_targets = import_project.database_target_images(values)
    expected_web_image = import_project.expected_webserver_image(values, args.webserver)

    plan_lines = [
        "# Import Migration Automation",
        "",
        f"- Project path: `{redactor.project_path(project_path)}`",
        f"- Namespace: `{args.namespace}`",
        f"- Private registry: `{args.registry or 'not configured'}`",
        f"- Image tag: `{args.image_tag}`",
        f"- Dump directory: `{args.dump_dir}`",
        f"- Execute mode: `{str(args.execute).lower()}`",
        f"- Redacted output: `{str(args.redact_sensitive).lower()}`",
        "",
        "## Automation Entry Points",
        "",
        "- `run-migration.sh` runs all guarded stages.",
        "- `scripts/01-sync-secrets.sh` applies Kubernetes Secrets from Compose secret environment values when explicitly allowed.",
        "- `scripts/02-build-and-push-images.sh` builds local application images and pushes them to the configured private registry.",
        "- `scripts/03-database-dump-restore.sh` dumps PostgreSQL-family sources and restores only targets defined in the private database target map.",
        "- `scripts/04-generate-routing-and-storage.sh` writes Traefik, ConfigMap, Secret, and PVC candidate manifests.",
        "- `scripts/05-validate.sh` re-runs the compatibility checker.",
        "",
        "## Guardrails",
        "",
        "- Dry-run is the default. Use `MIGRATION_EXECUTE=true` only on the trusted operator machine.",
        "- Secret and database stages require `MIGRATION_ALLOW_SECRET_MATERIAL=true` so secret values are read only at execution time.",
        "- Database restore requires a private `MIGRATION_DB_TARGETS` file with target DSNs.",
        "- Generated output must stay in `reports/` or another ignored/private directory.",
        "",
    ]
    import_project.render_migration_plan(
        lines=plan_lines,
        service_records=service_records,
        findings=findings,
        redactor=redactor,
        selected_ingress=args.ingress_controller,
        selected_webserver=args.webserver,
        selected_database=args.database,
        expected_web_image=expected_web_image,
        database_targets=database_targets,
    )
    write_file(output / "migration-automation.md", "\n".join(plan_lines) + "\n")

    common = (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f'PROJECT_PATH="${{PROJECT_PATH:-{project_path}}}"\n'
        f'VALUES="${{VALUES:-{args.values}}}"\n'
        f'NAMESPACE="${{NAMESPACE:-{args.namespace}}}"\n'
        f'MIGRATION_OUTPUT="${{MIGRATION_OUTPUT:-{output}}}"\n'
        f'MIGRATION_REGISTRY="${{MIGRATION_REGISTRY:-{args.registry}}}"\n'
        f'MIGRATION_IMAGE_TAG="${{MIGRATION_IMAGE_TAG:-{args.image_tag}}}"\n'
        f'MIGRATION_DUMP_DIR="${{MIGRATION_DUMP_DIR:-{args.dump_dir}}}"\n'
        f'MIGRATION_DB_TARGETS="${{MIGRATION_DB_TARGETS:-{args.db_targets or ""}}}"\n'
        f'MIGRATION_ALLOW_SECRET_MATERIAL="${{MIGRATION_ALLOW_SECRET_MATERIAL:-{str(args.allow_secret_material).lower()}}}"\n'
        'ALLOW_FLAG=""\n'
        'if [ "$MIGRATION_ALLOW_SECRET_MATERIAL" = "true" ]; then ALLOW_FLAG="--allow-secret-material"; fi\n'
    )
    callback = (
        'python3 "$REPO_ROOT/scripts/migrate_project.py" '
        '--project-path "$PROJECT_PATH" --values "$VALUES" --namespace "$NAMESPACE" '
        '--output "$MIGRATION_OUTPUT" --registry "$MIGRATION_REGISTRY" --image-tag "$MIGRATION_IMAGE_TAG" '
        '--dump-dir "$MIGRATION_DUMP_DIR" --db-targets "$MIGRATION_DB_TARGETS" '
        '--execute $ALLOW_FLAG '
    )
    write_file(
        output / "run-migration.sh",
        common
        + 'REPO_ROOT="${REPO_ROOT:-'
        + str(ROOT)
        + '}"\n'
        + f"{callback}--stage secrets\n"
        + f"{callback}--stage images\n"
        + f"{callback}--stage databases\n"
        + f"{callback}--stage manifests\n"
        + f"{callback}--stage validate\n",
        executable=True,
    )
    stage_scripts = {
        "01-sync-secrets.sh": "secrets",
        "02-build-and-push-images.sh": "images",
        "03-database-dump-restore.sh": "databases",
        "04-generate-routing-and-storage.sh": "manifests",
        "05-validate.sh": "validate",
    }
    for script_name, stage in stage_scripts.items():
        write_file(
            output / "scripts" / script_name,
            common
            + 'REPO_ROOT="${REPO_ROOT:-'
            + str(ROOT)
            + '}"\n'
            + f"{callback}--stage {stage}\n",
            executable=True,
        )

    db_target_example = {
        "databaseTargets": {
            "service-name-or-alias": "postgresql://target_user:target_password@target-service.namespace.svc:5432/target_db"
        }
    }
    write_file(output / "db-targets.example.yaml", yaml.safe_dump(db_target_example, sort_keys=False))


def stage_secrets(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    secrets = []
    for record, service in service_pairs:
        entries = secret_entries(service)
        if entries:
            secrets.append((record, entries))
    print(f"Secret-bearing services: {len(secrets)}")
    if not args.execute:
        return
    if not args.allow_secret_material:
        raise SystemExit("Refusing to read/apply secret material without --allow-secret-material.")
    for record, entries in secrets:
        manifest = {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {
                "name": k8s_name(record.name, "import-env"),
                "namespace": args.namespace,
                "labels": {"app.kubernetes.io/managed-by": "urban-platform-import"},
            },
            "type": "Opaque",
            "stringData": entries,
        }
        run_command(["kubectl", "-n", args.namespace, "apply", "-f", "-"], stdin=yaml.safe_dump(manifest, sort_keys=False))


def stage_images(args: argparse.Namespace, project_path: Path, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    candidates = []
    for record, service in service_pairs:
        if record.kind != "application" and not record.build_only:
            continue
        image = record.image
        build = service.get("build")
        needs_tag = record.build_only or (image is not None and (not image.tag or image.tag in import_project.MUTABLE_TAGS))
        if needs_tag:
            candidates.append((record, service, build))
    print(f"Application image promotion candidates: {len(candidates)}")
    if not args.execute:
        return
    if not args.registry:
        raise SystemExit("Refusing image promotion without --registry or MIGRATION_REGISTRY.")
    for record, service, build in candidates:
        target_image = f"{args.registry.rstrip('/')}/{k8s_name(record.name)}:{args.image_tag}"
        compose_path = relative_compose_file(project_path, record.file)
        if build:
            if isinstance(build, dict):
                context = compose_path.parent / str(build.get("context", "."))
                dockerfile = str(build.get("dockerfile", "Dockerfile"))
            else:
                context = compose_path.parent / str(build)
                dockerfile = "Dockerfile"
            run_command(["docker", "build", "-t", target_image, "-f", dockerfile, "."], cwd=context.resolve())
        elif record.image:
            run_command(["docker", "tag", record.image.display, target_image])
        run_command(["docker", "push", target_image])


def stage_databases(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    targets = read_database_targets(args.db_targets)
    dump_dir = Path(args.dump_dir).expanduser()
    candidates = [
        (record, service)
        for record, service in service_pairs
        if record.kind in {"postgresql", "postgis", "timescaledb"}
    ]
    print(f"PostgreSQL-family migration candidates: {len(candidates)}")
    if not args.execute:
        return
    if not args.allow_secret_material:
        raise SystemExit("Refusing database dump/restore without --allow-secret-material.")
    dump_dir.mkdir(parents=True, exist_ok=True)
    for record, service in candidates:
        port = published_port(record)
        env = postgres_env(service)
        if not port or not env["password"]:
            print(f"Skipping {record.file}::{record.name}: missing published port or POSTGRES_PASSWORD.")
            continue
        alias = k8s_name(record.name)
        dump_file = dump_dir / f"{alias}.dump"
        run_env = os.environ.copy()
        run_env["PGPASSWORD"] = env["password"]
        run_command(
            [
                "pg_dump",
                "--format=custom",
                "--no-owner",
                "--no-acl",
                "--host",
                "127.0.0.1",
                "--port",
                port,
                "--username",
                env["user"],
                "--dbname",
                env["database"],
                "--file",
                str(dump_file),
            ],
            env=run_env,
        )
        target_dsn = targets.get(record.name) or targets.get(alias)
        if target_dsn:
            restore_env = os.environ.copy()
            run_command(
                [
                    "pg_restore",
                    "--clean",
                    "--if-exists",
                    "--no-owner",
                    "--dbname",
                    target_dsn,
                    str(dump_file),
                ],
                env=restore_env,
            )
        else:
            print(f"Dumped {alias}; no target DSN mapping found, so restore was skipped.")


def stage_manifests(args: argparse.Namespace, service_pairs: list[tuple[import_project.ServiceRecord, dict[str, Any]]]) -> None:
    output = Path(args.output).expanduser()
    manifests: list[dict[str, Any]] = []
    for record, service in service_pairs:
        if record.kind == "nginx" and import_project.has_edge_publish(record.ports):
            name = k8s_name(record.name)
            manifests.append(
                {
                    "apiVersion": "networking.k8s.io/v1",
                    "kind": "Ingress",
                    "metadata": {
                        "name": f"{name}-traefik",
                        "namespace": args.namespace,
                        "annotations": {"traefik.ingress.kubernetes.io/router.entrypoints": "websecure"},
                    },
                    "spec": {
                        "ingressClassName": "traefik",
                        "rules": [
                            {
                                "http": {
                                    "paths": [
                                        {
                                            "path": "/",
                                            "pathType": "Prefix",
                                            "backend": {
                                                "service": {"name": name, "port": {"number": 80}}
                                            },
                                        }
                                    ]
                                }
                            }
                        ],
                    },
                }
            )
    content = GENERATED_HEADER + yaml.safe_dump_all(manifests, sort_keys=False)
    path = output / "manifests" / "traefik-ingress-candidates.yaml"
    write_file(path, content)
    print(f"Wrote {path}")
    if args.execute and manifests:
        run_command(["kubectl", "-n", args.namespace, "apply", "-f", str(path)])


def stage_validate(args: argparse.Namespace) -> None:
    command = [
        "python3",
        str(ROOT / "scripts/import_project.py"),
        "--project-path",
        args.project_path,
        "--values",
        args.values,
        "--ingress-controller",
        args.ingress_controller,
        "--webserver",
        args.webserver,
        "--database",
        args.database,
        "--report",
        str(Path(args.output).expanduser() / "post-migration-check.md"),
    ]
    if args.redact_sensitive:
        command.append("--redact-sensitive")
    if args.execute:
        run_command(command)
    else:
        print("Validation command:")
        print(" ".join(command))


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate or execute guarded project migration automation.")
    parser.add_argument("--project-path", required=True)
    parser.add_argument("--values", default=str(DEFAULT_VALUES))
    parser.add_argument("--image-policy", default=str(import_project.DEFAULT_IMAGE_POLICY))
    parser.add_argument("--output", default="reports/import-migration")
    parser.add_argument("--namespace", default="urban-platform")
    parser.add_argument("--ingress-controller", choices=["traefik", "nginx"], default="traefik")
    parser.add_argument("--webserver", choices=["nginx", "apache-httpd", "apache-tomcat", "traefik"], default="nginx")
    parser.add_argument("--database", default="postgresql")
    parser.add_argument("--registry", default="")
    parser.add_argument("--image-tag", default="imported-0.1.0")
    parser.add_argument("--dump-dir", default="/var/lib/urban-platform/private/db-dumps")
    parser.add_argument("--db-targets", default="")
    parser.add_argument("--stage", choices=["bundle", "secrets", "images", "databases", "manifests", "validate", "all"], default="bundle")
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--allow-secret-material", action="store_true")
    parser.add_argument("--redact-sensitive", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_path, _compose_files, service_pairs, findings, values = load_context(args)
    if args.stage in {"bundle", "all"}:
        generate_bundle(args, project_path, service_pairs, findings, values)
    if args.stage in {"secrets", "all"}:
        stage_secrets(args, service_pairs)
    if args.stage in {"images", "all"}:
        stage_images(args, project_path, service_pairs)
    if args.stage in {"databases", "all"}:
        stage_databases(args, service_pairs)
    if args.stage in {"manifests", "all"}:
        stage_manifests(args, service_pairs)
    if args.stage in {"validate", "all"}:
        stage_validate(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
