{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "cip.namespace" . }}
  labels:
    {{- include "cip.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurity | default "baseline" | quote }}
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurity | default "baseline" | quote }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurity | default "baseline" | quote }}
{{- end }}
